// UCSI预科招生 · 国内市场深度调研报告 - 完整数据集
// 设计风格：商业白皮书 · 深靛蓝+翡翠绿配色 · 杂志式排版

// ===== 渠道数据 =====
export const channelData = [
  {
    id: "xiaohongshu",
    name: "小红书",
    icon: "📕",
    color: "#FF2442",
    bgColor: "#FFF0F2",
    mau: "3亿",
    userProfile: "84%女性，18-34岁，一二线城市为主",
    educationTag: "出国留学、母婴、学习方法",
    acquisitionCost: "10元/私信咨询",
    conversionRate: "高（精准流量）",
    contentForm: "图文笔记（9图）+ 聚光投流",
    difficulty: 3,
    priority: 5,
    phase: "第一阶段",
    strategy: [
      "搭建品牌号+学姐人设号双账号矩阵",
      "每周3-5篇笔记，早7-9点/晚8-10点发布",
      "企业号认证（600元）+ 聚光投流（首充2000元）",
      "转化路径：笔记→评论区→私信→加微信→社群→成交",
      "核心指标：评论区「怎么联系」「滴滴」等显性消费词",
    ],
    kpiData: "半年涨粉5000+，引流3500+客户，成交近200单（行业案例）",
    kolTiers: [
      { level: "头部KOL", fans: "10万+", cost: "5000-20000元/篇", conversion: "1-3%", note: "品牌声量" },
      { level: "腰部KOL", fans: "1-10万", cost: "1000-5000元/篇", conversion: "5-10%", note: "主力转化" },
      { level: "尾部KOC", fans: "1000-1万", cost: "200-1000元/篇", conversion: "口碑铺垫", note: "大规模铺量" },
      { level: "素人博主", fans: "<1000", cost: "50-200元/篇", conversion: "真实感", note: "降低决策门槛" },
    ],
    hotTopics: [
      "UCSI预科学费只要4万？我帮你算了笔账",
      "高考失利别慌！10万预算也能上QS前300",
      "中职生也能留学！我是怎么逆袭的",
      "马来西亚留学5大坑，千万别踩！",
      "UCSI vs 泰莱 vs 双威，预科怎么选？",
      "音乐生必看！UCSI音乐学院全球排名32",
    ],
  },
  {
    id: "douyin",
    name: "抖音",
    icon: "🎵",
    color: "#000000",
    bgColor: "#F5F5F5",
    mau: "7亿+",
    userProfile: "35岁以下占70%，一二线城市偏多，教育内容女性偏好高",
    educationTag: "K12/家庭教育、艺术培训、语言教育",
    acquisitionCost: "中等（信息流广告+小风车）",
    conversionRate: "中等，需配合私域承接",
    contentForm: "竖屏短视频（15-60秒）+ 直播 + 小风车留资",
    difficulty: 4,
    priority: 5,
    phase: "第一阶段",
    strategy: [
      "短视频：前3秒必须抓眼球，用反转/冲突/痛点开头",
      "直播：每周1-2次，实时答疑，小风车卡片引流至企微",
      "信息流广告：投放落地页，表单留资后一键跳转加微",
      "DOU+投流：优质视频加热，精准定向18-35岁家长群体",
      "账号矩阵：机构官号+顾问个人号+在读学生号",
    ],
    kpiData: "头部留学机构抖音ROI稳定在1:5以上，直播场均留资50-200条",
    kolTiers: [
      { level: "头部达人", fans: "100万+", cost: "2-10万/条", conversion: "品牌曝光", note: "借势打名气" },
      { level: "腰部达人", fans: "10-100万", cost: "3000-2万/条", conversion: "3-8%", note: "精准种草" },
      { level: "垂直KOC", fans: "1-10万", cost: "500-3000/条", conversion: "5-12%", note: "高互动转化" },
      { level: "素人UGC", fans: "<1万", cost: "置换/200元内", conversion: "真实背书", note: "口碑铺量" },
    ],
    hotTopics: [
      "高考400分，我现在在QS前300的大学读书（反转式）",
      "同样是留学，为什么我选马来西亚而不是英国？（对比式）",
      "高考失利的孩子，还有机会上好大学吗？（痛点共鸣式）",
      "UCSI校园一日vlog | 真实留学生活（生活记录式）",
      "中介说的保录取是真的吗？（避坑揭秘式）",
      "一年10万在马来西亚能过什么样的生活？（好奇心式）",
    ],
  },
  {
    id: "wechat",
    name: "微信生态",
    icon: "💬",
    color: "#07C160",
    bgColor: "#F0FBF4",
    mau: "13亿",
    userProfile: "全年龄段，私域核心阵地，72%中国学生通过微信检索留学信息",
    educationTag: "私域转化、口碑传播、社群运营",
    acquisitionCost: "最低（私域流量）",
    conversionRate: "最高（信任基础最强）",
    contentForm: "公众号长文 + 社群运营 + 朋友圈 + 视频号",
    difficulty: 2,
    priority: 5,
    phase: "第一阶段",
    strategy: [
      "公众号：每周2-3篇深度长文（3000-5000字），SEO优化",
      "社群：建立3-5个咨询群（每群200-500人），每日1条干货",
      "朋友圈：每天1-2条，晒offer/校园生活/费用对比/限时活动",
      "视频号：同步抖音内容，借助微信生态分发",
      "企业微信：客户标签管理，精准跟进，自动化欢迎语",
    ],
    kpiData: "私域转化率是公域的3-5倍，口碑转介绍成本最低、转化率最高",
    kolTiers: [
      { level: "公众号KOL", fans: "10万+", cost: "1-5万/篇", conversion: "品牌背书", note: "深度种草" },
      { level: "社群KOL", fans: "活跃社群", cost: "置换/合作", conversion: "高（信任强）", note: "精准转化" },
      { level: "朋友圈达人", fans: "500-5000好友", cost: "低", conversion: "极高", note: "熟人背书" },
    ],
    hotTopics: [
      "【深度】马来西亚UCSI大学完全攻略（2025最新版）",
      "【案例】高考380分的她，如何进入QS前300大学",
      "【政策】中国教育部认证的马来西亚大学名单（附查询方法）",
      "【对比】UCSI vs 泰莱 vs 双威：预科全方位对比",
      "【答疑】家长最关心的20个马来西亚留学问题",
    ],
  },
  {
    id: "bilibili",
    name: "B站",
    icon: "📺",
    color: "#00A1D6",
    bgColor: "#F0F9FD",
    mau: "3.4亿",
    userProfile: "95后学生党为主，24岁以下占43%，高知群体，内容要求高",
    educationTag: "语言学习、高考考研、职业技能、留学攻略",
    acquisitionCost: "较低（内容驱动，无需大量投流）",
    conversionRate: "中等（决策周期长，但质量高）",
    contentForm: "横屏中长视频（5-20分钟）+ 专栏文章",
    difficulty: 5,
    priority: 3,
    phase: "第二阶段",
    strategy: [
      "内容要求极高：有料、有诚意、有创意，不能糊弄",
      "选题：留学避坑指南、UCSI深度测评、马来西亚留学生活vlog",
      "与UP主合作：软性植入「我的留学避坑指南」，提及机构",
      "专栏文章：深度攻略，SEO优化，长期积累搜索流量",
      "弹幕互动：积极回复评论，建立UP主人设",
    ],
    kpiData: "B站教育类UP主粉丝粘性强，单视频可积累长期流量，适合品牌建设",
    kolTiers: [
      { level: "百万UP主", fans: "100万+", cost: "5-20万/条", conversion: "品牌曝光", note: "权威背书" },
      { level: "十万UP主", fans: "10-100万", cost: "1-5万/条", conversion: "3-8%", note: "深度种草" },
      { level: "万粉UP主", fans: "1-10万", cost: "500-5000/条", conversion: "5-15%", note: "垂直精准" },
    ],
    hotTopics: [
      "我在马来西亚UCSI读预科的真实体验（20分钟深度vlog）",
      "马来西亚留学完全指南：从申请到入学全流程",
      "高考失利后，我选择了马来西亚留学（真实故事）",
      "UCSI音乐学院 vs 国内音乐学院：我的选择",
      "马来西亚留学避坑指南：这些坑我都踩过",
    ],
  },
  {
    id: "kuaishou",
    name: "快手",
    icon: "⚡",
    color: "#FF5500",
    bgColor: "#FFF4F0",
    mau: "4亿+",
    userProfile: "三线及以下城市占65%，小镇青年为主，老铁文化，信任度高",
    educationTag: "职业教育、技能教育、三农，留学赛道相对蓝海",
    acquisitionCost: "较低（下沉市场竞争少）",
    conversionRate: "高（老铁粘性强，私域转化好）",
    contentForm: "竖屏短视频 + 直播 + 快手课堂",
    difficulty: 3,
    priority: 3,
    phase: "第二阶段",
    strategy: [
      "定位：专攻三四线城市中职生/高考失利生家庭",
      "内容风格：接地气、真实感强，用方言/普通话口语化表达",
      "直播：老铁文化，主播要有亲和力，实时答疑转化",
      "快手课堂：发布免费留学攻略课，引流至私域",
      "私域：快手粉丝粘性强，转化率高于抖音",
    ],
    kpiData: "快手下沉市场留学赛道竞争少，中职生家庭群体信息差大，获客成本低",
    kolTiers: [
      { level: "头部主播", fans: "100万+", cost: "3-10万/场", conversion: "品牌曝光", note: "下沉市场声量" },
      { level: "腰部主播", fans: "10-100万", cost: "5000-3万", conversion: "5-10%", note: "精准转化" },
      { level: "草根KOC", fans: "<10万", cost: "低/置换", conversion: "高（老铁信任）", note: "口碑裂变" },
    ],
    hotTopics: [
      "中专毕业也能上本科！马来西亚留学真的可以",
      "高考没考好的孩子，还有这条路！",
      "一年10万，孩子能在马来西亚读什么大学？",
      "马来西亚华人多，中文能通行，适合中国孩子",
      "UCSI大学学历回国认可吗？教育部认证的！",
    ],
  },
  {
    id: "zhihu",
    name: "知乎",
    icon: "🔵",
    color: "#0084FF",
    bgColor: "#F0F6FF",
    mau: "1亿+",
    userProfile: "本科及以上占74%，高知高收入群体，深度决策型用户",
    educationTag: "科普、职业技能、留学攻略（深度内容）",
    acquisitionCost: "中等（知+投放）",
    conversionRate: "中高（深度种草，决策质量高）",
    contentForm: "问答回复 + 长文章 + 知+信息流广告",
    difficulty: 3,
    priority: 4,
    phase: "第一阶段",
    strategy: [
      "回答高流量问题：「马来西亚留学值得吗」「UCSI大学怎么样」",
      "长文章：5000-10000字深度攻略，SEO优化，长期积累流量",
      "知+投放：精准定向有留学意向的用户",
      "建立专业人设：留学顾问/过来人身份，增加可信度",
      "引导私信：在回答末尾留微信/公众号，引流至私域",
    ],
    kpiData: "知乎「马来西亚留学」相关问题浏览量100万+，「高考失利怎么办」200万+",
    kolTiers: [
      { level: "知乎大V", fans: "10万+", cost: "合作/置换", conversion: "品牌背书", note: "权威认证" },
      { level: "专业答主", fans: "1-10万", cost: "低成本", conversion: "高（精准用户）", note: "深度种草" },
    ],
    hotTopics: [
      "马来西亚留学值得吗？（浏览量100万+）",
      "UCSI大学怎么样？（浏览量50万+）",
      "高考失利怎么办？（浏览量200万+）",
      "10万预算能去哪个国家留学？（浏览量80万+）",
      "中职生可以出国留学吗？",
    ],
  },
  {
    id: "baidu",
    name: "百度",
    icon: "🔍",
    color: "#2932E1",
    bgColor: "#F0F1FF",
    mau: "6亿+",
    userProfile: "搜索型用户，有明确需求，决策意向强",
    educationTag: "主动搜索留学信息，转化意向最强",
    acquisitionCost: "高（200元/点击，6000元/有效客户）",
    conversionRate: "3%（点击转化），但意向度最高",
    contentForm: "SEM竞价广告 + SEO优化 + 百科词条 + 问答营销",
    difficulty: 4,
    priority: 3,
    phase: "第二阶段",
    strategy: [
      "SEM：投放「马来西亚留学」「UCSI大学」「马来西亚预科」等核心词",
      "SEO：优化官网，争取「马来西亚留学」自然排名前3",
      "百度百科：完善UCSI大学词条，增加可信度",
      "百度问答：回答留学相关问题，植入品牌信息",
      "百度贴吧：在留学吧、马来西亚留学吧活跃",
    ],
    kpiData: "百度SEM单次点击约200元，每30次点击产生1个有效用户，转化率约3%",
    kolTiers: [],
    hotTopics: [
      "马来西亚留学费用（月均搜索量5万+）",
      "UCSI大学怎么样（月均搜索量2万+）",
      "马来西亚预科（月均搜索量1万+）",
      "高考失利留学（月均搜索量3万+）",
      "思特雅大学（月均搜索量8000+）",
    ],
  },
  {
    id: "toutiao",
    name: "今日头条/百家号",
    icon: "📰",
    color: "#E8321A",
    bgColor: "#FFF3F1",
    mau: "4亿+",
    userProfile: "30-50岁中年用户为主，三四线城市渗透率高，家长群体集中",
    educationTag: "教育资讯、政策解读、深度长文",
    acquisitionCost: "中等（信息流广告）",
    conversionRate: "中等",
    contentForm: "长图文 + 信息流广告 + 热点借势",
    difficulty: 2,
    priority: 3,
    phase: "第二阶段",
    strategy: [
      "内容定位：面向家长群体，政策解读+教育资讯+案例分享",
      "信息流广告：精准定向30-50岁有孩子的家长",
      "热点借势：高考放榜、志愿填报季加大投放",
      "百家号：同步发布，扩大内容分发范围",
      "头条问答：回答教育相关问题，积累权威形象",
    ],
    kpiData: "头条家长群体集中，高考季（6-8月）是投放黄金期，CPC约50-100元",
    kolTiers: [],
    hotTopics: [
      "高考失利后，这条出路越来越多家庭选择",
      "马来西亚留学：中产家庭的性价比之选",
      "教育部认证！这所马来西亚大学凭什么QS前300",
      "中职生留学马来西亚：从专科到本科的逆袭之路",
      "留学消费降级？东南亚留学到底值不值",
    ],
  },
];

// ===== 用户画像数据 =====
export const userPersonas = [
  {
    id: "highschool",
    name: "普通高中生家庭",
    percentage: 40,
    icon: "🎓",
    color: "#3B82F6",
    studentAge: "17-19岁",
    parentAge: "40-50岁",
    income: "家庭年收入15-40万",
    region: "二三线城市（山东、河南、河北、四川、湖南、江西等）",
    score: "高中均分70-85%，高考300-450分",
    decisionCycle: "1-3个月",
    painPoints: [
      { point: "学历焦虑", desc: "孩子成绩不理想，国内只能上三本或专科，担心未来就业" },
      { point: "费用压力", desc: "英美澳年均30-50万太贵，家庭负担重" },
      { point: "信息不对称", desc: "不了解马来西亚大学质量，担心野鸡大学" },
      { point: "安全顾虑", desc: "对东南亚国家有刻板印象，担心治安和生活环境" },
      { point: "学历认证", desc: "担心回国后学历不被认可，影响考公考编" },
    ],
    decisionPath: [
      "高考成绩不理想",
      "搜索「低分留学」「性价比留学」",
      "小红书/抖音刷到马来西亚留学内容",
      "搜索「马来西亚留学费用」「UCSI大学怎么样」",
      "加微信咨询，对比多家机构",
      "决策报名（1-3个月）",
    ],
    ucsiMatch: "极高",
    keyMessage: "QS前300+中国教育部认证+年均10万，性价比最优解",
  },
  {
    id: "vocational",
    name: "中职/三校生家庭",
    percentage: 30,
    icon: "🔧",
    color: "#10B981",
    studentAge: "17-20岁",
    parentAge: "40-55岁",
    income: "家庭年收入10-25万",
    region: "三四线城市、县城为主",
    score: "无高考成绩或成绩较低，中专/职高/技校毕业",
    decisionCycle: "1个月内（快速决策）",
    painPoints: [
      { point: "升学路径不清晰", desc: "不知道中职生能申请什么大学，信息极度匮乏" },
      { point: "自卑心理", desc: "担心孩子学历低被歧视，不知道有留学这条路" },
      { point: "费用敏感", desc: "预算紧张，10万/年是心理上限" },
      { point: "就业导向", desc: "更关注毕业后能否找到好工作，而非学校排名" },
      { point: "信息渠道有限", desc: "三四线城市信息差大，容易被不良中介忽悠" },
    ],
    decisionPath: [
      "孩子中职毕业，不甘心只有中专学历",
      "搜索「中职生留学」「专升本留学」",
      "发现马来西亚接受中职生申请",
      "对比费用，UCSI预科4万/年可接受",
      "快速决策（1个月内）",
    ],
    ucsiMatch: "极高（竞争对手最少的蓝海群体）",
    keyMessage: "中职生可申请！1年预科直升本科，4年本硕连读，学历教育部认证",
  },
  {
    id: "arts",
    name: "艺术/音乐特长生",
    percentage: 20,
    icon: "🎵",
    color: "#8B5CF6",
    studentAge: "17-22岁",
    parentAge: "40-50岁",
    income: "家庭年收入20-50万",
    region: "一二线城市及省会城市",
    score: "有艺术/音乐基础，艺考失利或准备艺考",
    decisionCycle: "1-2个月",
    painPoints: [
      { point: "国内艺考压力大", desc: "竞争激烈，录取率低，优质院校更难进" },
      { point: "专业排名要求", desc: "希望孩子进入专业排名靠前的学校" },
      { point: "费用考量", desc: "英美音乐学院太贵，年均40-60万难以承受" },
      { point: "语言障碍", desc: "担心英语不够好，无法适应全英文教学" },
    ],
    decisionPath: [
      "艺考失利或准备艺考",
      "搜索「音乐留学」「艺术留学」「性价比音乐学院」",
      "发现UCSI音乐学院全球排名32",
      "对比费用，性价比极高",
      "快速决策（1-2个月）",
    ],
    ucsiMatch: "极高（UCSI音乐学院全球32名，无可替代的差异化卖点）",
    keyMessage: "UCSI音乐学院全球TOP32，费用仅为英美的1/4，马来西亚华语环境友好",
  },
  {
    id: "migration",
    name: "移民/陪读家庭",
    percentage: 10,
    icon: "✈️",
    color: "#F59E0B",
    studentAge: "15-22岁",
    parentAge: "35-45岁",
    income: "家庭年收入40万+",
    region: "一二线城市，有移民意向",
    score: "成绩不限，主要看家庭需求",
    decisionCycle: "3-6个月（决策复杂）",
    painPoints: [
      { point: "一举两得需求", desc: "希望孩子留学的同时，家长也能移民/陪读" },
      { point: "政策了解不足", desc: "不了解马来西亚第二家园计划、陪读签证等政策" },
      { point: "生活成本规划", desc: "需要详细了解马来西亚生活成本和居住环境" },
    ],
    decisionPath: [
      "有移民或长期居住马来西亚的意向",
      "搜索「马来西亚第二家园」「马来西亚陪读」",
      "了解到孩子可以在UCSI就读",
      "综合考量移民政策+教育资源",
      "决策（3-6个月）",
    ],
    ucsiMatch: "高（UCSI吉隆坡校区，生活配套完善）",
    keyMessage: "马来西亚第二家园+孩子就读UCSI，一举两得的最优方案",
  },
];

// ===== KOL博主对标数据 =====
export const kolBenchmarks = {
  xiaohongshu: [
    {
      level: "头部",
      name: "马来留学小岳",
      fans: "3-8万",
      style: "干货攻略型",
      avgLikes: "500-2000",
      contentFocus: "马来西亚大学对比、申请攻略、费用解析",
      monetization: "机构合作+自营招生",
      learningPoint: "用数据说话，费用对比图表化，收藏率高",
    },
    {
      level: "腰部",
      name: "在马学姐阿紫",
      fans: "1-3万",
      style: "生活体验型",
      avgLikes: "200-800",
      contentFocus: "留学生活分享、校园vlog、美食探店",
      monetization: "机构合作",
      learningPoint: "真实感强，粉丝信任度高，私信转化好",
    },
    {
      level: "腰部",
      name: "马来留学避坑指南",
      fans: "5000-2万",
      style: "避坑揭秘型",
      avgLikes: "300-1500",
      contentFocus: "中介黑名单、野鸡大学曝光、签证攻略",
      monetization: "流量变现+机构合作",
      learningPoint: "争议性内容互动率高，但需谨慎合规",
    },
    {
      level: "尾部KOC",
      name: "UCSI在读生分享",
      fans: "500-3000",
      style: "学长学姐型",
      avgLikes: "50-300",
      contentFocus: "第一人称真实经历分享",
      monetization: "推广佣金",
      learningPoint: "真实度最高，建立信任最有效",
    },
  ],
  douyin: [
    {
      level: "头部",
      name: "留学大叔说",
      fans: "50-200万",
      style: "口播知识型",
      avgLikes: "1000-5000",
      contentFocus: "留学政策解读、性价比对比、家长答疑",
      monetization: "机构合作+课程销售",
      learningPoint: "家长群体喜欢权威感，口播+字幕效果好",
    },
    {
      level: "腰部",
      name: "马来西亚留学日记",
      fans: "10-50万",
      style: "生活vlog型",
      avgLikes: "500-3000",
      contentFocus: "校园生活、吉隆坡探店、留学生日常",
      monetization: "机构合作+带货",
      learningPoint: "vlog内容留存率高，适合品牌长期投放",
    },
    {
      level: "腰部",
      name: "留学顾问小李",
      fans: "5-20万",
      style: "顾问人设型",
      avgLikes: "200-1000",
      contentFocus: "申请流程、材料准备、签证攻略",
      monetization: "直接招生",
      learningPoint: "顾问人设转化率高，私信咨询量大",
    },
  ],
};

// ===== 代理商体系数据 =====
export const agencySystem = {
  bEnd: {
    title: "B端主动拓展型代理",
    desc: "主动招募专业机构和个人，建立稳定的合作网络",
    tiers: [
      {
        name: "钻石代理",
        color: "#60A5FA",
        annual: "100人+/年",
        commission: "5000元/人",
        bonus: "达100人奖励5万，达200人奖励15万",
        support: ["专属客服", "校方见面会优先", "品牌授权书", "独家区域保护"],
        target: ["大型留学机构", "教育集团", "知名KOL"],
      },
      {
        name: "黄金代理",
        color: "#FBBF24",
        annual: "50-100人/年",
        commission: "4500元/人",
        bonus: "达50人奖励2万",
        support: ["营销物料支持", "定期培训", "专属顾问"],
        target: ["中型留学机构", "语培机构", "高中合作"],
      },
      {
        name: "白银代理",
        color: "#9CA3AF",
        annual: "20-50人/年",
        commission: "4000元/人",
        bonus: "无",
        support: ["基础营销物料", "线上培训"],
        target: ["小型工作室", "个人顾问", "教育自媒体"],
      },
      {
        name: "普通代理",
        color: "#D97706",
        annual: "<20人/年",
        commission: "3500元/人",
        bonus: "无",
        support: ["申请流程指导"],
        target: ["兼职代理", "家长推广大使升级"],
      },
    ],
    recruitChannels: [
      { channel: "语培机构（雅思/托福）", potential: "高", note: "学生有留学需求，天然匹配" },
      { channel: "二三线城市高中", potential: "高", note: "直接对接目标学生，信息差大" },
      { channel: "中职/职高学校", potential: "极高", note: "被大机构忽视的蓝海渠道" },
      { channel: "留学同行（其他国家）", potential: "中", note: "交叉合作，互补资源" },
      { channel: "教育自媒体/KOL", potential: "高", note: "流量变现，双赢合作" },
      { channel: "海外华人（马来西亚当地）", potential: "中", note: "本地资源，口碑背书" },
    ],
  },
  cEnd: {
    title: "C端客户裂变型代理（类微商模式）",
    desc: "家长报名后自动成为推广大使，推荐其他家长获得佣金，形成裂变",
    levels: [
      {
        level: "一级分销",
        name: "直接推荐",
        commission: "1500元/人",
        condition: "自己孩子已报名UCSI预科",
        example: "张妈妈推荐李妈妈报名，获得1500元",
      },
      {
        level: "二级分销",
        name: "间接推荐",
        commission: "500元/人",
        condition: "A推荐B，B推荐C，A获得500元",
        example: "张妈妈→李妈妈→王妈妈，张妈妈获得500元",
      },
      {
        level: "三级分销",
        name: "深度裂变",
        commission: "200元/人",
        condition: "A推荐B，B推荐C，C推荐D，A获得200元",
        example: "张妈妈→李妈妈→王妈妈→赵妈妈，张妈妈获得200元",
      },
    ],
    incentives: [
      { name: "阶梯奖励", desc: "推荐3人额外奖励1000元，推荐5人额外奖励3000元" },
      { name: "月度排行榜", desc: "TOP1奖励5000元，TOP2奖励3000元，TOP3奖励2000元" },
      { name: "团队长晋升", desc: "推荐10人成为推广大使，升级为团队长，享受团队业绩1%分红" },
      { name: "即时到账", desc: "成交后立即到账50%佣金，学生入学后到账剩余50%" },
    ],
    tools: [
      { name: "专属推广码", desc: "每个家长有唯一推广码，精准追踪来源" },
      { name: "推广物料包", desc: "海报、文案、视频素材一键下载" },
      { name: "推广大使专属群", desc: "定期分享话术和成功案例" },
      { name: "小程序管理", desc: "实时查看佣金收入、团队人数、提现记录" },
    ],
    compliance: [
      "只设置三级分销，不超过三级，规避传销风险",
      "佣金与产品价值挂钩，不虚高定价",
      "不收取代理费，家长报名后自动成为推广大使",
      "所有佣金明细透明可查，T+7到账",
    ],
  },
};

// ===== 渠道获客成本对比 =====
export const channelCostData = [
  { channel: "小红书", cpa: 10, unit: "元/私信咨询", conversion: 85, priority: 5 },
  { channel: "微信私域", cpa: 30, unit: "元/有效线索", conversion: 90, priority: 5 },
  { channel: "口碑转介绍", cpa: 50, unit: "元/线索", conversion: 95, priority: 5 },
  { channel: "抖音信息流", cpa: 200, unit: "元/线索", conversion: 60, priority: 4 },
  { channel: "知乎", cpa: 150, unit: "元/线索", conversion: 70, priority: 4 },
  { channel: "快手", cpa: 100, unit: "元/线索", conversion: 65, priority: 3 },
  { channel: "今日头条", cpa: 180, unit: "元/线索", conversion: 55, priority: 3 },
  { channel: "百度SEM", cpa: 6000, unit: "元/有效客户", conversion: 40, priority: 2 },
];

// ===== 行动路线图 =====
export const actionRoadmap = [
  {
    phase: "第一阶段",
    period: "0-3个月",
    title: "冷启动·建立基础设施",
    color: "#3B82F6",
    tasks: [
      "注册小红书企业号（600元）+开通聚光投流（首充2000元）",
      "搭建微信生态：公众号+企业微信+3个咨询社群",
      "开通抖音账号，前30条视频建立账号权重",
      "知乎注册，回答5-10个高流量留学问题",
      "设计推广物料包（海报/文案/视频素材）",
      "招募10-20个种子代理（B端机构+C端家长）",
      "建立CRM系统，记录客户跟进进度",
    ],
    kpi: "小红书粉丝500+，微信社群300人，种子代理10个，首批成交3-5人",
  },
  {
    phase: "第二阶段",
    period: "3-12个月",
    title: "规模化·多渠道矩阵",
    color: "#10B981",
    tasks: [
      "小红书：每周5篇笔记，开始聚光投流，月均私信咨询50+",
      "抖音：每周7条视频，开始直播（每周2次），小风车留资",
      "快手：开通账号，专攻三四线城市中职生群体",
      "B站：每月2-3条深度视频，建立权威形象",
      "百度SEO：优化官网，争取核心词前3名",
      "B端代理扩展至50-100个",
      "C端推广大使达到200-500个",
      "开展线下宣讲会（每月2-3场，聚焦二三线城市）",
    ],
    kpi: "月招生20-50人，B端代理50个，C端推广大使200个，月营收8-20万",
  },
  {
    phase: "第三阶段",
    period: "12个月+",
    title: "成熟期·自运转体系",
    color: "#8B5CF6",
    tasks: [
      "建立内容工厂：专职内容团队，日产5条优质内容",
      "KOL矩阵：签约3-5个腰部KOL，长期合作",
      "B端代理100+，全国覆盖",
      "C端推广大使1000+，裂变体系自运转",
      "开发小程序：推广中心+佣金系统+申请追踪",
      "建立学生大使体系：在读UCSI学生成为品牌代言人",
      "年度代理商大会，分享成功案例，激励竞争",
    ],
    kpi: "月招生100-200人，年营收400-800万，代理商贡献80%招生量",
  },
];

// ===== 收益估算 =====
export const revenueModel = [
  { scenario: "保守", monthly: 20, annual: 240, commission: 4000, revenue: 96, cost: 30, profit: 66 },
  { scenario: "基准", monthly: 50, annual: 600, commission: 4000, revenue: 240, cost: 60, profit: 180 },
  { scenario: "乐观", monthly: 100, annual: 1200, commission: 4000, revenue: 480, cost: 100, profit: 380 },
  { scenario: "规模化", monthly: 200, annual: 2400, commission: 4000, revenue: 960, cost: 180, profit: 780 },
];
